### ISSUE TITLE
Add profile picture support for accounts

### ISSUE THREAD

**Issue by jayrc7** [jayrc7/Movie-of-the-week#9]
Simply add that functionality in the profile page, DO NOT modify other pages to support profile pictures. Those changes will come later. Must allow the user to choose a picture from their local storage, be able to crop/rotate, and allow it to be changed or removed entirely. Use an appropriate default image (e.g. silhouette of a person). Design must be approved by CODEOWNERS.

**Comment by varu777** [comment]
HI! I am trying to contribute on this issue. But I am not getting why the project is not running on my machine.  When I am running the index.html page nothing is appearing. Can you help me out with this.

**Comment by jayrc7** [comment]
Sounds good! Whenever you can email me here so I can send you the environment files. cabrerajason7@gmail.com

**Comment by varu777** [comment]
> ###

Hi I have sent you a mail.

**Comment by jayrc7** [comment]
Sent you the info!
